#!/bin/bash

# 64 000 000 bits / video length = target bitrate

PWD_USER=$(pwd)
MAX_VIDEO_SIZE="60000000"
MAX_AUDIO_SIZE="4000000"

# mix the $1 and PWD_USER to get the full path
# $1 is the path to the video
# PWD_USER is the path to the current directory
# the result is the full path to the video the make the new variable called "VPATH"
VPATH=$(echo "$1" | sed "s|$PWD_USER|$PWD_USER|g")

# Check args

if [[ "$1" == "" ]]; then
	echo "Error: No video file selected"
	echo "Usage: mp4min <video-file>"
	exit
fi

# Check if file is video, getting the duration

DURATION=$(ffprobe -hide_banner "$VPATH" -show_entries format=duration -v quiet -of csv="p=0")

if [[ "$DURATION" == "" ]]; then
	echo Error, ffprobe returned no duration. "$VPATH" is possibly not a video file
	exit
fi

echo "$1" is a video file and is $DURATION seconds long

# Calc bitrate

ADJUSTED_DURATION=$(printf "%.0f\n" "$DURATION")
VIDEO_BITRATE=$(echo $((MAX_VIDEO_SIZE / ADJUSTED_DURATION*60/100)))
AUDIO_BITRATE=$(echo $((MAX_AUDIO_SIZE / ADJUSTED_DURATION*75/100)))

ffmpeg -hide_banner -i "$VPATH" -c:v libvpx-vp9 -b:v "$VIDEO_BITRATE" -vf scale=1280:720 -c:a libopus -b:a "$AUDIO_BITRATE" "$VPATH-compressed.webm"
